<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <title><![CDATA[@={meta.blog.title}]]></title>
    <link href="@={meta.blog.site}"/>
    <link href="@={meta.url}" rel="self"/>
    <updated>@={meta.isoDate}</updated>
    <id>@={meta.blog.site}</id>
    <author>
        <name><![CDATA[@={meta.blog.author}]]></name>
    </author>
    <generator uri="http://embedthis.com/expansive/">Expansive</generator>
    <@ content @>
</feed>
