                <@ 
                    if (meta.blog.twitter) { 
                        addItems('scripts', 'scripts/tweet.js')
                     @>
                        <span class="twitter">
                            <a href="https://twitter.com/share" class="twitter-share-button"
                                data-via="@={meta.blog.twitter.id}">Tweet</a>
                        </span>
                <@ } @>
