{
    layout: ''
}
    <div class="summary">
        <time datetime="@={meta.date}" pubdate><@= meta.date.format('%b %e, %Y') @></time>
        <h1><a href="@~@={meta.url}"><@= meta.title @></a></h1>
        <@ content @>
        <div class="read">
            <a class="ui right labeled icon gray button" href="@~@={meta.url}">
                <i class="right long arrow icon"></i>
                Read
            </a>
        </div>
    </div>
